version: 0.0
os: linux

files:
#   - source: /test.jsp
#     destination: /root/tomcat/webapps/ROOT
#   - source: /index.html
#     destination: /var/www/html
#
    - source: /dbtest.jsp
      destination: /root/tomcat/webapps/ROOT
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root 
