version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Building
  post_build:
    commands:
      ## aws s3 cp target/*.war s3://myhhbucket23 . We don't need this step.
      - echo Build completed
artifacts:
  files:
    - dbtest.jsp
    - test.jsp
    - index.html
    - scripts/server_start.sh
    - scripts/server_stop.sh
    - appspec.yml
   
  discard-paths: yes
